### PR TITLE
Console consumer tool [WIP]

### PR DESCRIPTION
**Pull request by joshuafleck**
@PeterWuMC - I have created a console that publishes RabbitFeed events. Let me know if you think this could be useful!

Sample output:
```
$ be rabbit_feed console --environment development --config spec/fixtures/configuration.yml
RabbitFeed console starting at 2016-02-05 18:03:30 UTC...
Environment: development
Queue: development.rabbit_feed
Ready. Press CTRL+C to exit.
-----------------------------cmm_lead_created: 2016-02-05 18:05:32 UTC-----------------------------
#Event metadata
application: call_me_maybe
created_at_utc: 2016-02-05T18:05:32.032543Z
environment: development
host: macjfleck.int.xbridge.com
name: cmm_lead_created
schema_version: 2.0.0
version: 1.0.0
****************************************************************************************************
#Event payload
alt_telephone_number: 
email_address: xyz1@example.com
full_name: Mr. John Smith
lead_id: 56b4e46c3c4bd42ff6000001
policy_number: 
rfq_reference: XYZ1
telephone_number: 02071234567
----------------------------------------------------------------------------------------------------
```

### CODE REVIEW

**Comment by joshuafleck** [comment]
TODO: use a dedicated queue

**Comment by PeterWuMC** [comment]
You are going to be facing the same issue as me, because you are consuming everything from any application and any event.  Pooka events will be consumed here and randomly serialised payload will be display. Will be quite annoying in scenario like... Chopin, generate an rfq. This triggers pooka and call rabbit feeds events... Not sure how you would do that in the spirit of not loading or even mentioning pooka into this public gem.

**Comment by joshuafleck** [comment]
> Not sure how you would do that in the spirit of not loading or even mentioning pooka into this public gem.

I'm not actually concerned by this issue. Users of the console may not care/be aware of the distinction between RabbitFeed and Pooka. In our ecosystem, which uses both, we can simply use the Pooka console. The Pooka console will print out regular RabbitFeed events, but also has the ability to deserialise Pooka payloads, see: https://github.com/simplybusiness/pooka/pull/146/files#diff-f6fbef433526b4d9d111c440d353ee3cR20

**Comment by PeterWuMC** [comment]
Signed-off-by @peterwumc

**Pull request merged**
