### PR TITLE
Rails 5 compatibility changes

### PR DESCRIPTION
**Pull request by dncrht**
Make this gem Rails 5 compatible

@dragosmiron @gzzsound @mineshdattani @Sam-Levene @sivanpatel @andrewgristwood

### CODE REVIEW

**Comment by dncrht** [comment]
I'm very unfamiliar with this gem, and the problem comes from upstream. I'll try to have a look, but in any case we're not breaking anything new.

**Comment by dragosmiron** [comment]
@joshuafleck ^

**Comment by Sam-Levene** [comment]
Both Dani and I couldn't see this bad rubocop issue locally, so it, most likely, can be ignored

**Comment by sivanpatel** [comment]
@Sam-Levene that's strange, I can see it locally

**Comment by joshuafleck** [comment]
How do these changes make the gem Rails 5 compatible? @dncrht

**Comment by joshuafleck** [comment]
@dncrht @Sam-Levene I've resolved the Rubocop issues in https://github.com/simplybusiness/rabbit_feed/pull/55, but I would still like to understand the goal of this PR before allowing it to be merged. Please see: https://github.com/simplybusiness/rabbit_feed/pull/54#issuecomment-307335969

**Comment by dncrht** [comment]
@joshuafleck at certain point (4 weeks ago) I had bundler complaining about active_support not able to work with Rails 5. I've tried now and I haven't had that problem so it's safe to ignore this PR

**Pull request closed without merging**
